apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
spec:
  type: NodePort
  selector:
    app: url-shortener
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30007 # optional: system assigns one if not given
